### ISSUE TITLE
Suggest Change:  "Material to Use" Dropdown - make it a Textbox, Use the list of materials as Labels inside the Textbox of "material to use"

### ISSUE THREAD

**Issue by ralch34** [philrhoy/IMCCVenueReservationSystem2023#42]
Suggestion: Material to Use Dropdown changes... (change it to "Materials Needed" Text Box, instead of dropdown but the list of materials are the labels of the text).

For the "Notes" TextBox, change the label (inside the textbox)
From "Notes will be provided by Property Custodian or Admin"
 to...
 "Notes will be provided by Property Custodian. i.e. for Acknowledgement, date or venue changes due to circumstance, and other reasons. Notes will be provided by Admin here."

For "Material to Use" TextBox, change the label (inside the textbox)  to...
"Notes for materials needed as provided by Property Custodian. i.e. includes Microphone 1pc, Epson Projector 1pc, Additional Chairs,..."

![Screenshot_31 changes on Material to Use part 2](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/1fa069ca-3939-4754-8166-94a4485ad9b0)
![Screenshot_31 changes on Material to Use](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/3f1639ff-f161-4a1f-9849-746ee8bf9ed9)

**Comment by philrhoy** [comment]
Any concern on this issue?

**Comment by ralch34** [comment]
> Any concern on this issue?
@philrhoy 
"is it redundant? to have two columns "notes" and "material to use"  (i plan to turn it into textbox instead of dropdown, because it needs the PTC to select multiple materials and not just one. - the dropdown just selects one material - that's my concern.)
