### ISSUE TITLE
Bug: Error Lines Found both on Prop.C. and Admin User when Reviewing Newly Created Reservations.

### ISSUE THREAD

**Issue by ralch34** [philrhoy/IMCCVenueReservationSystem2023#44]
![Screenshot_16 on newly created res by STO but Admin  can see error](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/92f27966-1531-464e-8ef7-271975cc56e1)
![Screenshot_18](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/c867f5db-3b26-454a-836e-981631e6e5e6)

**Comment by ralch34** [comment]
@philrhoy  nacheck nani nimo nga lines 129?

**Comment by philrhoy** [comment]
> @philrhoy nacheck nani nimo nga lines 129?

Wala man error. I think fixed na ni after nimo mag update database? @ralch34 

**please close the issue once fixed.**
![image](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/86213120/87e14b9f-689c-4281-b7c4-7cfb405a6c5c)

**Comment by ralch34** [comment]
I don't encounter the error "edit_reservation.php line 129" anymore. Ill close it
