### ISSUE TITLE
Bug: Calendar View - "Clear" Button not responding.

### ISSUE THREAD

**Issue by ralch34** [philrhoy/IMCCVenueReservationSystem2023#47]
MiniBug: Calendar View - "Clear" Button not responding.
when I select a month and filters... it does display its respective reservations.. but "clear" button not working
![Screenshot_1](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/f08aedc9-ef37-45c8-a55b-07e90021badf)

**Comment by philrhoy** [comment]
[Clear Button.webm](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/86213120/b64c1601-051b-46d0-b798-1baba9d36566)
Please see the video, it's working naman yung clear button.

**Comment by ralch34** [comment]
> [Clear Button.webm](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/86213120/b64c1601-051b-46d0-b798-1baba9d36566) Please see the video, it's working naman yung clear button.


see this video. its not working on my side  
https://drive.google.com/file/d/1Bv77mZV83pF65e9VSlPC6BSkOXx3Y8r0/view?usp=sharing

**Comment by ralch34** [comment]
the clear button is working. Thankss. issue closed
