### ISSUE TITLE
2. Add More Details in Pop-up Box in Clicking Colored Boxes in Calendar (Dates and Times txtboxes are too short - make pop-up box wider)

### ISSUE THREAD

**Issue by ralch34** [philrhoy/IMCCVenueReservationSystem2023#91]
Calendar Interface: Add ‘Start Time’ and ‘End Time’ details in Pop-up Box Details of color-coded Reservations in the calendar. Also, Add Program detail.

![Screenshot_4](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/3c3adc84-de7d-4223-9ec1-278aa5eb0d76)

**Comment by ralch34** [comment]
Good Pm... Can you make it more compact? kay ang labels Date Start and Date End... mulapas beyond sa browser tab.... visible lng siya kung naka full-screen ang user's browser... Or as suggested by you... can put the dates and times in the same line. (itapad nlang)

![Screenshot_2](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/681adf37-e1ab-45f3-bd46-1f1694bb7a5b)
![Screenshot_3](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/aaa79255-8f8e-41f8-bcbd-0860795f60b4)

**Comment by philrhoy** [comment]
![image](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/86213120/688bd3d0-b112-4371-bb0b-e19209255d1f)
Please review the screenshot if same sa imo local. Don't forget to pull the changes.

**Comment by ralch34** [comment]
> ![image](https://private-user-images.githubusercontent.com/86213120/293597853-688bd3d0-b112-4371-bb0b-e19209255d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjcxMjAsIm5iZiI6MTcwNDE2NjgyMCwicGF0aCI6Ii84NjIxMzEyMC8yOTM1OTc4NTMtNjg4YmQzZDAtYjExMi00MzcxLWJiMGItZTE5MjA5MjU1ZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAzNDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMmY2MmVhODRmNWUxYzM5ZTFhOWY4NmJkMDczODVjZWRmNDZkN2Q4MDg1NmI3MmY0M2M0OTNkYjE3ZWE3NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7V4AQsW3lFwX0xNe7ffHYpsRx-mCQV3as8G-yeYltpE) Please review the screenshot if same sa imo local. Don't forget to pull the changes.

@philrhoy the Dates and Times text boxes is too short...  maybe expand the whole pop-up box itself?
![Screenshot_14](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/48e5e8b7-b567-49ec-aa98-423501a89c18)

**Comment by ralch34** [comment]
![image](https://github.com/philrhoy/IMCCVenueReservationSystem2023/assets/90671718/7b259c4a-c2b9-432b-8a6f-7a9528a051fc)
its working after clear cache
